# Generated by Django 5.0.6 on 2024-07-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_delete_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attend_date',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField()),
                ('student', models.ManyToManyField(to='users.student')),
            ],
        ),
    ]
