# Generated by Django 5.0.6 on 2024-07-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_attendance_parent_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
